### ISSUE TITLE
resolving resulted in empty path when resolving absolute .

### ISSUE THREAD

**Issue by ExpHP** [vitiral/path_abs#16]
The path `"."` cannot be resolved.

```rust
extern crate path_abs;
use path_abs::PathArc;

fn main() {
    println!("{}", PathArc::new(".").absolute().unwrap().display());
}
```

**Comment by Screwtapello** [comment]
If this is not already fixed, it should be fixed by #27.

**Comment by ExpHP** [comment]
confirmed by building against master (though the fix is not yet released)

**Comment by ExpHP** [comment]
This fix still hasn't been released...

**Comment by vitiral** [comment]
sorry about that! 0.5.0 has now been released!
