### ISSUE TITLE
What should happen when canonicalizing `..` at the root?

### ISSUE THREAD

**Issue by Screwtapello** [vitiral/path_abs#22]
Currently, on POSIX:

```rust
let maybe_path = PathArc::new("/foo/../..").absolute();
println!("{:?}", maybe_path);
// -> Err(Error<resolving resulted in empty path when resolving absolute /foo/../..>)
```

Meanwhile, on Windows:

```rust
let maybe_path = PathArc::new(r"C:\foo\..\..").absolute();
println!("{:?}", maybe_path);
// -> Ok("\\\\?\\C:")
```

...which says "Ok" but is actually an invalid path (since it has an "extended path syntax" prefix component, but no root component). Adding more parent components (`C:\foo\..\..\..\..\`) produces the same result, but no error.

Meanwhile, on both POSIX and Windows, typing `cd ..` in a root directory does nothing.

I'm guessing that the current platform-specific behaviour is a bug, but if we have to pick a behaviour for all platforms, should it be "error", "silently clamp", or something else?

**Comment by vitiral** [comment]
yuk.

My first impulse is to let the lower level details handle it, but my second impulse is that being platform dependent is bad so we should try and eliminate that.

I think the second impulse is correct and I also hate it when things fail silently -- so this should be an error for both platforms. I would try to mimic the POSIX error and standardize it for both if possible.

Also, you are right that it does "nothing":
```
➜  ~ cd /
➜  / cd ..
➜  / echo $?
0
```

I don't think that's behavior we should emulate.

**Comment by Screwtapello** [comment]
Based on the behaviour of `cd`, there's already a behaviour that's consistent cross-platform and which people are likely to expect (doing nothing), but the main use I can think of is [directory traversal attacks](https://en.wikipedia.org/wiki/Directory_traversal_attack) so that's probably not something we should encourage.

I guess if we change our minds in the future, we can be *less* strict, but being *more* strict would create a backwards-compatibility issue, so we should default to strictness.

**Comment by vitiral** [comment]
This was probably fixed a while ago, most likely by you :smile:
