### ISSUE TITLE
PartialOrd and PartialEq traits

### ISSUE THREAD

**Issue by ChuckDaniels87** [vitiral/path_abs#25]
I have started to play a bit your crate in my application ([RnR](https://github.com/ChuckDaniels87/rnr)) because I had some problems with `canonicalize()` resolving symlinks. It seems that `path_abs` solves some of them.

I was wondering if you are planning to support *PartialOrd* and *PartialEq* traits in `path_abs` structs since they are already implemented on *Path* and *PathBuf*.  I can think in several use cases for that.

Nice job btw!

**Comment by ChuckDaniels87** [comment]
> It should already be implemented actually?

Totally my fault!! I thought `comp()` was part of `PartialOrd`, but is in `Ord` trait instead. *PathAbs* is working as expected with `PartialOrd` and `PartialEq`. 

On the other hand, `Ord` and `Eq` traits are also implemented for *Path* and *PathBuf*. It would be interesting to have them. Should I open a different issue or rename this one?

**Comment by vitiral** [comment]
Go ahead and rename this one, and feel free to open a PR to add *Ord* and
*Eq*

**Comment by ChuckDaniels87** [comment]
> Go ahead and rename this one, and feel free to open a PR to add *Ord* and *Eq*

No need, they are working as expected. Sorry for the noise!

**Comment by vitiral** [comment]
👍
