### ISSUE TITLE
Types probably shouldn't implement the `Deref` trait.

### ISSUE THREAD

**Issue by Screwtapello** [vitiral/path_abs#28]
The Rust API guidelines [say](https://rust-lang-nursery.github.io/api-guidelines/predictability.html#only-smart-pointers-implement-deref-and-derefmut-c-deref):

> The `Deref` traits are used implicitly by the compiler in many circumstances, and interact with method resolution. The relevant rules are designed specifically to accommodate smart pointers, and so the traits should be used only for that purpose.

If I understand correctly, `path_abs` uses `Deref` to put its various path types into an inheritance hierarchy, but "Deref-as-inheritance" is [often](https://stackoverflow.com/questions/45086595/is-it-considered-a-bad-practice-to-implement-deref-for-newtypes) [considered](https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deref.md) an anti-pattern.

When I was working on PR#27, in the code that builds up a path I instinctively reached for `.push()` since I expected to make a lot of changes. When I wrote something like this:

```rust
let mut res = PathAbs::new(path);
res.push(something);
```

...I got an error on the second line saying something like "cannot borrow immutable reference as mutable" *and* a warning on the first line saying "variable is marked `mut` but doesn't need to be", a combination that confused me for some time. Eventually I figured out that the `.push()` method was visible because of the `Deref` trait, but couldn't be used because of the lack of `DerefMut`. Since we can't really implement `DerefMut` because of `Arc`, we should probably drop `Deref`.

Once I'd figured it out, I switched to:

```rust
let mut res = PathAbs::new(path);
res = res.join(something);
```

...but that failed too. In this situation, `.join()` is inherited from `PathArc`, so it returns a `PathArc` instead of a `PathAbs`, and what I really need is:

```rust
let mut res = PathAbs::new(path);
res = PathAbs(res.join(something));
```
...which I would have found more quickly if `Deref` hadn't given me a `.join()` that didn't quite work the way I wanted.

**Comment by vitiral** [comment]
So when I originally wrote this library I thought of `PathArc` (and it's descendants) as basically smart pointers for `PathBuf` -- which is why I implemented `Deref` for them.

As the library has grown they have really grown to be much more than that. I need to consider this issue more, but you may very well be right that implementing `Deref` was the wrong call. There are honestly not very many methods _left_ from the stdlib `Path` that we would need to implement to make it 100% compatible. Also it already implements `AsRef<Path>` and `AsRef<PathBuf>` so we should be pretty good 😄

**Comment by Screwtapello** [comment]
From #27:

> I wonder if it would make sense to have a trait `PathExt` which we implement for `std::Path` and `std::PathBuf` which overrides the various methods for better errors. That would allow anyone (including us!) to get these better error messages with the core types. Then we could implement `PathExt` for all of our types. It could also help in discouraging the use of `PathArc` (heck, `PathArc` really would just be a deref'd `PathBuf`).

**Comment by vitiral** [comment]
I made some edits since then:


> I wonder if it would make sense to have a trait PathExt which we implement for std::Path and std::PathBuf which overrides the various methods for better errors. That would allow anyone (including us!) to get these better error messages with the core types. Then we could implement PathExt for all of our types. It could also help in discouraging the use of PathArc (heck, PathArc really would just be a deref'd PathBuf).

> A similar thing could be done for the File* types (FileExt) to have the core file type there be cleaner. Then I think (I forget the details) that we could have the trait implement the io::Write+Read traits, which might also clean up a bunch of code here.

> Edit: with such a trait, I think I would definitely be willing to get rid of PathArc and have the related "unwrapping" methods just return Arc<PathBuf>. Let me know if there are any corner cases I'm not considering, but this seems pretty solid...

**Comment by Screwtapello** [comment]
I've been looking into this. Before I forget all the blind alleys I went down, let me write some notes:

I started with a `PathExt` trait, copying most of the methods from `Path` and `PathBuf`, but changing the return type to be `path_abs::Error` instead of `io::Error` where appropriate. However, since `Path` is a different type from `&PathBuf`, it wouldn't be possible to implement any of the self-modifying methods like `push()`, so I split the trait into `PathExtReadOnly` (methods taking `&self`, implementable for `Path`, `PathBuf` and `Arc<PathBuf>`) and `PathExt` (the above, plus methods taking `&mut self`, implementable for `PathBuf`).

That nicely mirrored the `Path`/`PathBuf` split, but those types aren't *really* independent, since `Path` has methods that return `PathBuf`. To model this, I added an `Output` type alias to `PathExtReadOnly`, where `Path` methods returned `PathBuf`, I had `PathExtReadOnly` methods return `Self::Output`. However, there needs to be a way to take a type that implements `PathExtReadOnly` and return a type that implements `PathExt` containing the same value, so you can make modifications to the copy. I cast about for a suitable name for such a method, and came up with `to_owned()`. But wait, isn't that supposed to be part of the `ToOwned` trait?

Yes, `ToOwned` is almost exactly what I want—it's specifically designed to model the relationship between `Path` and `PathBuf`! So I removed the `Output` type alias and changed all the relevant return types from `Self::Output` to `<Self as ToOwned>::Owned`. Unfortunately, in such a model we want methods on `Arc<PathBuf>` to return `PathBuf` just like methods on `&Path` do, but `Arc<T>` does not implement `ToOwned`.

Eventually I discovered `Arc<T>::make_mut()`, a zero (extra) cost abstraction that makes it easy to modify an `Arc` value in-place, by automatically cloning it when needed. Using `make_mut()`, it's super-easy to implement read-only and read-write methods for `PathBuf` and `Arc<PathBuf>`, so I joined both traits back into a single `PathExt` trait where all the relevant return types are just `Self`. This means the trait can't be implemented for `&Path`, but hopefully that won't crop up much in this library.

Compared to the methods of `Path` and `PathBuf`, this new trait:

- removes `as_os_str()`, `to_str()`, `to_string_lossy()` since they're just convenience wrappers for functionality we can get from `AsRef<OsStr>`
- removes `into_os_string()` and `into_boxed_path()` since those smell like methods that should be on an actual type, not on a trait.
- removes `to_path_buf()` because the trait might be implemented for something that's not related to  `PathBuf`.
- removes `strip_prefix()` since that feels like it should be some kind of `PathAbs::relative_to(&self, container: PathAbs)` rather than a method on every path ever.
- removes `read_dir()` since in the world of `path_abs` that's really `PathAbs::into_dir()` (although `read_dir()` is a better name, I think)
- renames `pop()` to `truncate_to_parent()` since `push()` got removed (see below) and it would be weird to have one and not the other.
- adds `truncate_to_root()` since that's an operation I needed in the make-absolute algorithm and it didn't already exist

Since you've mentioned that you don't like the "adjoining path" semantics of `Path::join()` and `PathBuf::push()`, I figured `PathExt` should remove those methods in favour of others with simpler semantics. My current plan is to replace them with `concat()` and `append()` respectively (renamed so people don't expect the original semantics) and make them require a pure-relative path. If you pass them a path that contains Prefix, RootDir or ParentDir components, they'll return an error. I'm not 100% sold on this idea, though - feedback welcome!jjj

**Comment by Screwtapello** [comment]
I wrote:

> My current plan is to replace them with `concat()` and `append()` respectively

The CLI-WG [wrote](https://internals.rust-lang.org/t/pre-rfc-additional-path-handling-utilities/8405):

> The `PathBuf` will gain a new, non-destructive `append` function which will operate similarly to the already existing `push`.
>
> [...]
>
> The `Path` will gain a new function `concat` which operates simmilarly as `PathBuf::append`.

Great minds, etc. etc.

**Comment by vitiral** [comment]
Sound like quite a bit of work there. Unfortunately I'm not entirely sure I follow however. I _believe_ you are saying that the issue is that `PathExt` might not work because of the return types -- something that I had actually not considered very well when I suggested creating it. It makes me fairly worried it is not actually possible.

But you say it might be using `Self`... which could be possible. Can you outline what the trait would be and what it's methods would be?

If you think it is a reasonable approach you could also just implement it. I'm sure you're probably right.

**Comment by vitiral** [comment]
Wow, `Arc::make_mut` is super cool -- basically makes any `Arc` copy-on-write able.

Ya, go ahead and push a PR, I can try and provide some early feedback if helpful. And thanks for being more involved in the community than me ATM 😄

**Comment by vitiral** [comment]
We have removed `Deref` to all "normal" types, and I think we can remove the remaining uses:

```
$ rg Deref --after-context 2
src/edit.rs
261:impl Deref for FileEdit {
262-    type Target = FileOpen;
263-

src/write.rs
235:impl Deref for FileWrite {
236-    type Target = FileOpen;
237-

src/file.rs
528:impl Deref for PathFile {
529-    type Target = PathAbs;
530-

src/ty.rs
158:impl Deref for PathType {
159-    type Target = PathAbs;
160-

src/dir.rs
449:impl Deref for PathDir {
450-    type Target = PathAbs;
451-

src/read.rs
138:impl Deref for FileRead {
139-    type Target = FileOpen;
140-

```
