### ISSUE TITLE
WASI symlink implementation is incorrect

### ISSUE THREAD

**Issue by RReverser** [vitiral/path_abs#51]
Actually, wait, this PR is wrong. The file descriptor in the API is supposed to be a preopen directory descriptor, not the descriptor for the target file.

_Originally posted by @RReverser in https://github.com/vitiral/path_abs/issues/50#issuecomment-770120481_

**Comment by RReverser** [comment]
Until https://github.com/rust-lang/rust/issues/68574 is fixed, it's best to either use symlink via `libc`, or fallback to not supporting them altogether.

**Comment by vitiral** [comment]
I knew that... That's totally why I haven't merged yet...

**Comment by RReverser** [comment]
> That's totally why I haven't merged yet...

Can't tell if you're just joking or I'm misunderstanding what you're saying 🤔 The PR above is merged...

**Comment by RReverser** [comment]
FWIW I meanwhile made a PR to Rust to expose the correct API: https://github.com/rust-lang/rust/pull/81542

Let's see how that goes...

**Comment by vitiral** [comment]
Sorry, I meant it's the reason I haven't pushed and was joking. The reason I haven't pushed is 🅻🅸🅵🅴

I'll hold off on updating the library until someone tells me the implementation is correct. I'd be willing to also accept a PR to add a crate feature for `wasi` and use the wasi crate to implement the "correct" behavior, as suggested in rust-lang/rust#81542

**Comment by RReverser** [comment]
> Sorry, I meant it's the reason I haven't pushed and was joking. The reason I haven't pushed is 🅻🅸🅵🅴

Ah, that's how I understood it first too, but wanted to double-check :)

I have a pending PR to implement correct behaviour for symlinks, but first had to make some PRs to add WASI support to `tempfile` crate which is used for tests in this one.

Now that https://github.com/Stebalien/tempfile/pull/138 is merged, I'll be able to make a PR here soon-ish too.

**Comment by RReverser** [comment]
Fix in https://github.com/vitiral/path_abs/pull/52 (ignoring the tests for now, as the situation around temporary files in WASI is pretty tricky and the previous implementation didn't work with them either, so no point in blocking on them).
