### ISSUE TITLE
Moving/copying/removing a symbolic link

### ISSUE THREAD

**Issue by ExpHP** [vitiral/path_abs#6]
(I wish GitHub provided a better way to have discussion other than opening a bug report)

**Let's talk symlinks.**

I have an application which has historically taken the easy way out of path management by changing the current directory.  In moving away from this setup towards a more principled design, I considered using `path_abs` as a means of leveraging the type system to ensure that I don't accidentally leave behind any lingering relative paths.

Reviewing the documentation, however, it is evident to me that my mental model of symlinks differs from that of the library.  Of course, this is to be expected; I understand that PathAbs is opinionated, and that our ideas will inevitably clash *somewhere.*

But with regard to symlinks specifically, I find the model presented by this crate to be **dangerous, and quite scary!**  I'd like to hear your point of view on this, and I wonder if there is something I am missing.

---

I'll describe these clashing models by making analogy to Rust's borrow semantics.

To me:
* A directory in the filesystem is like some `Box<_>` type.  It has a unique owner (its "true" parent) and that's the only way you can move or delete it.
* A file in the filesystem is like some `Arc<_>` type.  It may have multiple owners via hard links, and dies when the last link vanishes.
* A symlink is like some `*mut _` type.  It can change data belonging to its target, but only if you explicitly dereference it (by joining another path component).  The pointer itself does not own its target, and its target might not even exist.

In PathAbs:
* by immediately resolving symlinks, PathAbs makes symlinks feel more like C++'s mutable references.  A symlink **is** the directory or file it points to.  To me, this is terrifying, because if I'm not careful, then code which was *intended* to delete a symlink could end up accidentally **recursively deleting its target!**

What do you think of this?  Do you disagree with this risk about deleting a symlink?  Is there room in PathAbs for symlinks to live as first class citizens?  Am I asking too many questions? :stuck_out_tongue:

**Comment by ExpHP** [comment]
I tried to put together something resembling what I think an API with support for symlinks *might* look like, without changing the semantics of anything that already existed.

The commit shows:
*  The addition of a type `PathEntry` which is like `PathAbs` but with a slightly weaker invariant that it doesn't resolve a symlink in the final path component.  This makes it not the canonical form of a file or directory, but rather, of a *directory entry;* hence the name.
* `PathSymlink` which holds a PathEntry to a path previously identified as a symlink.
* `PathDir::ListEntries`, which is capable of losslessly listing all entries of a directory as paths *in that directory*, in contrast to ListDir

**Comment by vitiral** [comment]
Sorry I haven't replied yet. This issue is very interesting to me, but
unfortunately my 6mo old spilled half a cup of coffee on my laptop a few
days ago and it's taking me a bit to set up my new computer with NixOS.

**Comment by vitiral** [comment]
Okay, I'm back and ready to look at a design which incorporates symlinks in some way.

## Usecase / Problem Statement

First, some definitions:
- _absolute path_: an absolute path is the absolute path to a fs object (file, directory, symlink). Some or even all of the directories in that path may be symlinks, but the beginning directory must always be root (or [`\\?\` on windows](https://stackoverflow.com/a/41233992/1036670)).
- _canonicalized path_: is an absolute path with no symlinks, including the destination.

The goal of this issue should be to use **absolute paths** as opposed to **cannonicalized paths**. I think this would solve all of your issues.

## Technical Solution
- If the path does not start with `/` then prefix it with `std::env::current_dir().canonicalize()`.
- If the path has `.` or `..` in it then handle as follows:
  - Remove `.` components
  - Remove `..` components that follow components by stripping out the component. I.e. `/foo/bar/../baz -> /foo/baz`.
  - If left with leading `..` get `std::env::current_dir().canonicalize()` and preform the above operation, requiring that it start with `/`.
- If on windows and the path does not start with `\\?\` then replace the first component with it's  `canonicalized()` form.

This is still a work in progress, I have to get off the bus...

**Comment by ExpHP** [comment]
Sounds like part of what you're describing is Path::clean ([stdlib PR](https://github.com/rust-lang/rust/pull/47363)).

Absolute paths would solve this problem and some others. What you've got drafted there at the time of me writing this sounds like a bit of a wild mix of canonicalization and cleaning; I'm not sure about Windows, but on Unix I think `current_dir().join(path).clean()` is usually all I am looking for.

**Comment by vitiral** [comment]
[this](https://github.com/rust-lang/rust/pull/47363#issuecomment-359606479) and [this](https://github.com/rust-lang/rust/pull/47363#issuecomment-372019693) are particularly enlightening. Fully supporting windows is _not easy_ and I think I would want to wait until at least _clean_ has landed.

**Comment by vitiral** [comment]
@kennytm I followed your comments on the rust issue and I'm wondering what your thoughts are for this issue.

The basic use case: we want "absolute paths for files that exist" -- but they are allowed to have symlinks inside.

In particular, do you think the technical solution I gave will work for windows?

**Comment by vitiral** [comment]
agh, I [hate my life](https://github.com/rust-lang-nursery/cli-wg/issues/10#issuecomment-374947099)

> This is not generally possible in POSIX because of symlinks: if a/b/c is a symlink to a/d, then a/b/c/../foo is actually a/foo, not a/b/foo. Now that modern versions of Windows support symlinks too, I suspect that's also an issue there.

that actually makes sense and makes me very sad.

**Comment by vitiral** [comment]
So, thinking a little more about this, I don't think there is really _any_ value in allowing `..` anywhere but the beginning. When does someone have a path like `/a/b/../c/d/../e/f`? That is a pretty absurd use-case IMO, and resolving it either correctly _or_ incorrectly could lead to a lot of confusion. Better to just error in my opinion.

So my suggestion: only allow (multiple) `..` at the beginning of the the path (so `../../a/b/c/d/e/f` would be valid).

The issue of resolving the wrong path doesn't exist when `..` is at the beginning since the `current_dir` is already canonicalized so we can safely walk down the path (we know it is "real").

**Comment by ExpHP** [comment]
I construct paths with interior `..` all the time when joining relative paths from config files...

**Comment by vitiral** [comment]
good point. I think treating it semantically is probably the best course of action, agreed?

**Comment by vitiral** [comment]
See #11, would love any feedback!

**Comment by ExpHP** [comment]
Define semantically? (Lexically?)

I alluded to this in an edit to one of my previous posts, but I'm beginning to think that automatic normalization of any form can be hazardous.  There are times when straight up canonicalization is best, and there are other times when cleaning first before canonicalization is best.

That said, I certainly will feel a lot more comfortable using the library when it isn't instantly following every symbolic link; so I do welcome any change to that effect.

**Comment by vitiral** [comment]
This should be solved as of #11. Please comment!

**Comment by vitiral** [comment]
solved > 0.4.0
