### ISSUE TITLE
Should prefer `impl From` over `impl Into`? (C-CONV-TRAITS)

### ISSUE THREAD

**Issue by ExpHP** [vitiral/path_abs#7]
impls of From are usually preferred because they are more general than Into.  See this API guideline https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-conv-traits

**Comment by vitiral** [comment]
sounds good, although I believe it is impossible when trying to `impl From<MyType> for std::path::Path` (for example).

**Comment by ExpHP** [comment]
Yes, I believe there are some cases where it's unavoidable.  The language "[Into] should never be implemented" used in the guideline is perhaps a bit strong.

**Comment by vitiral** [comment]
@Screwtapello did most of the work to get this done!
