### ISSUE TITLE
Making Stdio from {FileRead, FileWrite}

### ISSUE THREAD

**Issue by ExpHP** [vitiral/path_abs#9]
I don't see an easy way to use FileRead and FileWrite in `std::process::Command::{stdout, stderr, stdin}` as there's no way to get the File and they don't impl `Into<Stdio>`

**Comment by vitiral** [comment]
definitely need to implement `Into<File>` for all the `File*` types, that was an oversight.

**Comment by vitiral** [comment]
fixed in #15
